/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.crud.view;

import com.crud.control.dbConnection;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author calvin
 */
public class additme extends javax.swing.JFrame {
private Connection connection1;
String s;

    /**
     * Creates new form additme
     */
    public additme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mi = new javax.swing.JTextField();
        days = new javax.swing.JComboBox<>();
        dept = new javax.swing.JComboBox<>();
        otpay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        month = new javax.swing.JComboBox<>();
        lname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        bpay = new javax.swing.JTextField();
        photo = new javax.swing.JLabel();
        pos = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        gen = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Department:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 110, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Add employee");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 150, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Firts name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, 40));

        year.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 120, -1));

        fname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 410, 40));

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 140, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Middle initital:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 120, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Last name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 90, 40));

        mi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(mi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 410, 40));

        days.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        days.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Day","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31" }));
        jPanel1.add(days, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 120, -1));

        dept.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Production","Human-Resource management","Logistics","Research and development","Purchasing","Marketing" }));
        jPanel1.add(dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 408, 170, 30));

        otpay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(otpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 170, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Birthdate:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 90, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Address:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 90, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Overtime-pay:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 120, 40));

        month.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "month","1","2","3","4","5","6","7","8","9","10","11","12" }));
        jPanel1.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 110, -1));

        lname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 410, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Gender:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 90, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Basic pay:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 90, 40));

        address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 290, 40));

        bpay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(bpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 170, 40));

        photo.setText("Photo");
        jPanel1.add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 60, 410, 260));

        pos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(pos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 170, 40));

        jButton3.setText("Browse photo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 400, 140, 40));

        jButton4.setText("clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Position:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 90, 40));

        gen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male","Female" }));
        jPanel1.add(gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 170, -1));

        jMenu1.setText("home");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public final class Work extends JFrame{
  
    
    public Work(){
    
     
       
          
          JFileChooser file = new JFileChooser();
          file.setCurrentDirectory(new File(System.getProperty("user.home")));
          //filter the files
          FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
          file.addChoosableFileFilter(filter);
          File selectedFile;
          int result = file.showSaveDialog(null);
           //if the user click on save in Jfilechooser
          if(result == JFileChooser.APPROVE_OPTION){
              selectedFile = file.getSelectedFile();
              String path = selectedFile.getAbsolutePath();
              photo.setIcon(ResizeImage(path));
              s=path;
          }
           //if the user click on save in Jfilechooser




          else if(result == JFileChooser.CANCEL_OPTION){
              System.out.println("No File Select");
          }
        }
    
    

     
     // Methode to resize imageIcon with the same size of a Jlabel
    public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(photo.getWidth(), photo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      dbConnection dbConnect = dbConnection.getdbConnection();
        
       
          try{
               connection1 = dbConnect.getConnection();
         File m=new File(s);
               FileInputStream is = new FileInputStream(m);
               
               
               
             PreparedStatement ps2=connection1.prepareStatement("INSERT INTO employee(photo,Firstname,MI,Lastname,Birthday,Address,Position,Department,Dailypay,Otpay,Gender) VALUE(?,'"+fname.getText()+"','"+mi.getText()+"','"+lname.getText()+"','"+year.getText()+"-"+month.getSelectedItem()+"-"+days.getSelectedItem()+"','"+address.getText()+"','"+pos.getText()+"','"+dept.getSelectedItem()+"',"+bpay.getText()+","+otpay.getText()+",'"+gen.getSelectedItem()+"')");     
             ps2.setBinaryStream(1,is,(int)m.length());
             ps2.executeUpdate();   
              String pass=year.getText()+"-"+month.getSelectedItem()+"-"+days.getSelectedItem();
          PreparedStatement ps=connection1.prepareStatement("INSERT INTO `accounts` (`AccountID`, `Acctype`, `password`) VALUES ((Select empno from employee where firstname='"+fname.getText()+"' AND Lastname='"+lname.getText()+"'), 'employee', '"+pass+"')"); 
          ps.executeUpdate();
          JOptionPane.showMessageDialog(null,"Employee added to the record");
          fname.setText("");
          mi.setText("");
          lname.setText("");
          address.setText("");
          pos.setText("");
          year.setText("");
          bpay.setText("");
          otpay.setText("");
          photo.setIcon(null);
          dept.setSelectedItem(0);
          month.setSelectedItem(0);
          days.setSelectedItem(0);
          
             

          
          
          
  } catch (SQLException ex) { 
        Logger.getLogger(additme.class.getName()).log(Level.SEVERE, null, ex);
    } catch(Exception ex){
         ex.printStackTrace();
     } 
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Work a=new Work();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       fname.setText("");
          mi.setText("");
          lname.setText("");
          address.setText("");
          pos.setText("");
          year.setText("");
          bpay.setText("");
          otpay.setText("");
          photo.setIcon(null);
          dept.setSelectedItem(0);
          month.setSelectedItem(0);
          days.setSelectedItem(0);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
            this.setVisible(false);
       Menu a=new Menu();
       a.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(additme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(additme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(additme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(additme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new additme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField bpay;
    private javax.swing.JComboBox<String> days;
    private javax.swing.JComboBox<String> dept;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox<String> gen;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mi;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField otpay;
    private javax.swing.JLabel photo;
    private javax.swing.JTextField pos;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
