/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.crud.view;

import com.crud.control.dbConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author calvin
 */
public class employee extends javax.swing.JFrame {
private Connection connection1;
    /**
     * Creates new form employee
     */
    public employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        emno = new javax.swing.JLabel();
        pic1 = new javax.swing.JLabel();
        pic2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        pic4 = new javax.swing.JLabel();
        pos = new javax.swing.JLabel();
        pic6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emno.setText("Employee no:");
        jPanel1.add(emno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 170, 50));
        jPanel1.add(pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 13, 320, 230));

        pic2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pic2.setText("Welcome ");
        jPanel1.add(pic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 90, 50));

        name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name.setText("name");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 350, 50));

        pic4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pic4.setText("Position:");
        jPanel1.add(pic4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 80, 50));

        pos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pos.setText("Position:");
        jPanel1.add(pos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 360, 50));

        pic6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pic6.setText("Employee no:");
        jPanel1.add(pic6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, 50));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("Issue a request or complain");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 800, 60));

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton2.setText("View my payrolls");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 800, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 540));

        jMenu1.setText("Log-out");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        
         
        this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       complain a=new complain();
       a.emno.setText(emno.getText());
        a.setVisible(true);
    a.pack();
    a.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        
           // TODO add your handling code here:
        
      emppayslip a=new emppayslip();
     try{
        PreparedStatement pst1;
        ResultSet rs1;
        dbConnection dbConnect = dbConnection.getdbConnection();
        connection1 = dbConnect.getConnection();
        String course="SELECT paydates.transactionid,paydates.StartDate,paydates.CutOffDate FROM employee,paydates,salary WHERE Salary.empno=employee.empno AND paydates.TransactionID=Salary.TransactionID AND Salary.empno="+emno.getText();
        pst1=connection1.prepareStatement(course);
        rs1=pst1.executeQuery();
        a.trans.setModel(DbUtils.resultSetToTableModel(rs1));
        a.emno.setText(emno.getText());
            a.setVisible(true);
    a.pack();
    a.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
         }catch(SQLException e){
             JOptionPane.showMessageDialog(null,"not connected");
         } 
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel emno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel name;
    public javax.swing.JLabel pic1;
    public javax.swing.JLabel pic2;
    public javax.swing.JLabel pic4;
    public javax.swing.JLabel pic6;
    public javax.swing.JLabel pos;
    // End of variables declaration//GEN-END:variables
}
