/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.crud.view;

import com.crud.control.dbConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author calvin
 */
public class salaryinput extends javax.swing.JFrame {
private Connection connection1;
    /**
     * Creates new form salaryinput
     */
    public salaryinput() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tno = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        emno = new javax.swing.JLabel();
        ot = new javax.swing.JTextField();
        dy = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\calvin\\Pictures\\pics\\py.PNG")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 400));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Employee no:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, -1));

        tno.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tno.setText("n");
        getContentPane().add(tno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 200, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Transation no:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Date:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 60, -1));

        date.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        date.setText("d");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 430, -1));

        emno.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        emno.setText("Date:");
        getContentPane().add(emno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 190, -1));

        ot.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ot.setText("Overtime hours");
        ot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otActionPerformed(evt);
            }
        });
        getContentPane().add(ot, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 190, -1));

        dy.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        dy.setText("Days of work");
        dy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dyActionPerformed(evt);
            }
        });
        getContentPane().add(dy, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 190, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\calvin\\Pictures\\pics\\slip.png")); // NOI18N
        jLabel3.setText("Generate a Slip");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void otActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otActionPerformed

    private void dyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dyActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        double sssvalue,taxvalue,phvalue,sss=.0363,tax=.03,ph=.0275;
        double sal = 0,ots = 0,totals,dpay,otpay,net;
        double dys=Double.parseDouble(dy.getText()),ott=Double.parseDouble(ot.getText());
     try{
        PreparedStatement pst1,pst;
        ResultSet rs1;
        dbConnection dbConnect = dbConnection.getdbConnection();
        connection1 = dbConnect.getConnection();
        String s="SELECT Dailypay,Otpay FROM employee WHERE empno="+emno.getText();
        pst1=connection1.prepareStatement(s);
        rs1=pst1.executeQuery();
      if(rs1.next()){
       ots=rs1.getDouble(2);
       sal=rs1.getDouble(1);
      }
      
        totals=(ots*ott)+(dys*sal);
        sssvalue=sss*totals;
        taxvalue=totals*tax;
        phvalue=totals*ph;
        dpay=dys*sal;
        otpay=ots*ott;
        
        net=totals-(sssvalue+taxvalue+phvalue);
        
        
        String i="UPDATE `salary` SET `Net`="+net+",`OT`="+otpay+",`Philhealth`="+phvalue+",`tax`="+taxvalue+",`SSS`="+sssvalue+",`status`='paid',`Salary`="+totals+" WHERE `TransactionID`="+tno.getText()+" AND empno="+emno.getText();
        pst=connection1.prepareStatement(i);
        pst.executeUpdate();
        
        this.setVisible(false);
        
        
        JasperDesign jdesign=JRXmlLoader.load("D:\\Sad-system\\src\\com\\crud\\view\\payroll.jrxml");
        
        JRDesignQuery updateQuery=new JRDesignQuery();
         updateQuery.setText("SELECT employee.Firstname,employee.MI,employee.Lastname,employee.Position,employee.Department,paydates.StartDate,paydates.CutOffDate,salary.Net,salary.OT,salary.Philhealth,salary.tax,salary.SSS,salary.Salary FROM salary,paydates,employee WHERE employee.empno=salary.empno AND salary.TransactionID=paydates.TransactionID AND salary.TransactionID="+tno.getText()+" AND salary.empno="+emno.getText());
         jdesign.setQuery(updateQuery);
         
         JasperReport jreport=JasperCompileManager.compileReport(jdesign);
         JasperPrint jprint=JasperFillManager.fillReport(jreport,null,connection1);
        
        
        JasperViewer.viewReport(jprint,false);
        
        
        
        
      
            }catch (SQLException ex) {
        Logger.getLogger(manageitem.class.getName()).log(Level.SEVERE, null, ex);
    } catch (JRException ex) {
        Logger.getLogger(salaryinput.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
        
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salaryinput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salaryinput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salaryinput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salaryinput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salaryinput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel date;
    private javax.swing.JTextField dy;
    public javax.swing.JLabel emno;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JTextField ot;
    public javax.swing.JLabel tno;
    // End of variables declaration//GEN-END:variables
}
